name: codemod_core
version: 1.1.0
homepage: https://github.com/Workiva/dart_codemod
publish_to: https://onepub.dev/api/jbbxpsdavu/
description: A sample command-line application.
environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies: 
  analyzer: ^6.0.0
  glob: ^2.1.2
  io: ^1.0.4
  lint_hard: ^4.0.0
  logging: ^1.2.0
  meta: ^1.11.0
  mockito: ^5.4.2
  path: ^1.8.3
  quiver: ^3.2.1
  source_span: ^1.10.0
  stack_trace: ^1.11.1
dev_dependencies: 
  dcli: ^3.2.0
  lints: ^2.0.0
  test: ^1.21.0
  test_descriptor: ^2.0.1
