name: codemod_core
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  analyzer: ^6.0.0
  io: ^1.0.4
  logging: ^1.2.0
  mockito: ^5.4.2
  path: ^1.8.3
  quiver: ^3.2.1
  source_span: ^1.10.0
  stack_trace: ^1.11.1
  # path: ^1.8.0

dev_dependencies:
  dcli: ^3.2.0
  lints: ^2.0.0
  test: ^1.21.0
  test_descriptor: ^2.0.1
